#ifndef AIPP_6F7C135EA1682095423401977B710E77BF617D9A
#define AIPP_6F7C135EA1682095423401977B710E77BF617D9A

// ======================================================================
// NOTICE  NOTICE  NOTICE  NOTICE  NOTICE  NOTICE  NOTICE  NOTICE  NOTICE
// ----------------------------------------------------------------------
//
// DO NOT EDIT THIS FILE DIRECTLY.
//
// This source file has been generated by Atlas Strong Type Generator v1.0.0
// https://github.com/jodyhagins/Atlas
//
// DO NOT EDIT THIS FILE DIRECTLY.
//
// ----------------------------------------------------------------------
// NOTICE  NOTICE  NOTICE  NOTICE  NOTICE  NOTICE  NOTICE  NOTICE  NOTICE
// ======================================================================

#if __has_include(<version>)
#include <version>
#endif
#include <concepts>
#include <cstddef>
#include <cstdint>
#include <format>
#include <functional>
#include <iostream>
#include <type_traits>
#include <utility>

#ifndef WJH_ATLAS_50E620B544874CB8BE4412EE6773BF90
#define WJH_ATLAS_50E620B544874CB8BE4412EE6773BF90

// ======================================================================
// ATLAS STRONG TYPE BOILERPLATE
// ----------------------------------------------------------------------
//
// This section provides the infrastructure for Atlas strong types.
// It is identical across all Atlas-generated files and uses a shared
// header guard (WJH_ATLAS_50E620B544874CB8BE4412EE6773BF90) to ensure
// the boilerplate is only included once even when multiple generated
// files are used in the same translation unit.
//
// The boilerplate is intentionally inlined to make generated code
// self-contained with zero external dependencies.
//
// Components:
// - atlas::strong_type_tag: Base class for strong types
// - atlas::undress(): Universal value accessor for strong types
// - atlas_detail::*: Internal implementation utilities
//
// For projects using multiple Atlas-generated files, this boilerplate
// will only be compiled once per translation unit thanks to the shared
// header guard below.
//
// ----------------------------------------------------------------------
// DO NOT EDIT THIS SECTION
// ======================================================================

// Atlas feature detection macros
#ifndef ATLAS_NODISCARD
#if defined(__cpp_attributes) && __cpp_attributes >= 201603L
#define ATLAS_NODISCARD [[nodiscard]]
#else
#define ATLAS_NODISCARD
#endif
#endif

#if defined(__cpp_impl_three_way_comparison) && \
    __cpp_impl_three_way_comparison >= 201907L
#include <compare>
#endif

#if defined(__cpp_lib_format) && __cpp_lib_format >= 202110L
#include <format>
#endif

namespace atlas {

template<typename T>
struct strong_type_tag
{
#if defined(__cpp_impl_three_way_comparison) && \
    __cpp_impl_three_way_comparison >= 201907L
    friend auto operator <=> (
        strong_type_tag const &,
        strong_type_tag const &) = default;
#endif
};

struct value_tag
{ };

namespace atlas_detail {

template <typename... Ts>
struct make_void
{
    using type = void;
};

template <typename... Ts>
using void_t = typename make_void<Ts...>::type;

template <std::size_t N>
struct PriorityTag
: PriorityTag<N - 1>
{ };

template <>
struct PriorityTag<0u>
{ };

using value_tag = PriorityTag<3>;

template <bool B>
using bool_c = std::integral_constant<bool, B>;
template <typename T>
using bool_ = bool_c<T::value>;
template <typename T>
using not_ = bool_c<not T::value>;
template <typename T, typename U>
using and_ = bool_c<T::value && U::value>;
template <typename T>
using is_lref = std::is_lvalue_reference<T>;

template <typename T>
using remove_cv_t = typename std::remove_cv<T>::type;
template <typename T>
using remove_reference_t = typename std::remove_reference<T>::type;
template <typename T>
using remove_cvref_t = remove_cv_t<remove_reference_t<T>>;
template <bool B, typename T = void>
using enable_if_t = typename std::enable_if<B, T>::type;
template <bool B>
using when = enable_if_t<B, bool>;

template <typename T>
using _t = typename T::type;

template <typename T, typename = void>
struct has_atlas_value_type
: std::false_type
{ };

template <typename T>
struct has_atlas_value_type<
    T,
    enable_if_t<not std::is_same<
        typename remove_cvref_t<T>::atlas_value_type,
        void>::value>>
: std::true_type
{ };

void atlas_value_for();
struct value_by_ref
{ };
struct value_by_val
{ };
struct ref_tag
{ };

// ----------------------------------------------------------------------------
// Base case: T does not have atlas_value_type
// These are the termination cases for the recursion.
// ----------------------------------------------------------------------------
template <typename T>
constexpr T &
value_impl(T & t, PriorityTag<0>, value_by_ref)
{
    return t;
}
template <typename T>
constexpr T const &
value_impl(T const & t, PriorityTag<0>, value_by_ref)
{
    return t;
}
template <typename T>
constexpr T
value_impl(T & t, PriorityTag<0>, value_by_val)
{
    return std::move(t);
}
template <typename T>
constexpr T
value_impl(T const & t, PriorityTag<0>, value_by_val)
{
    return t;
}

// ----------------------------------------------------------------------------
// Enum case: T is an enum - convert to underlying type
// Always returns by value since conversion creates a distinct value.
// ----------------------------------------------------------------------------
template <typename T>
constexpr auto
value_impl(T t, PriorityTag<2>, value_by_ref)
-> typename std::enable_if<
    std::is_enum<T>::value,
    typename std::underlying_type<T>::type>::type
{
    return static_cast<typename std::underlying_type<T>::type>(t);
}
template <typename T>
constexpr auto
value_impl(T t, PriorityTag<2>, value_by_val)
-> typename std::enable_if<
    std::is_enum<T>::value,
    typename std::underlying_type<T>::type>::type
{
    return static_cast<typename std::underlying_type<T>::type>(t);
}

// ----------------------------------------------------------------------------
// Recursive case: T has atlas_value_for() hidden friend
// Use ADL to call atlas_value_for() and recurse.
// ----------------------------------------------------------------------------
template <typename T>
constexpr auto
value_impl(T & t, PriorityTag<1>, value_by_ref)
-> decltype(value_impl(
    atlas_value_for(t),
    value_tag{},
    value_by_ref{}))
{
    return value_impl(atlas_value_for(t), value_tag{}, value_by_ref{});
}
template <typename T>
constexpr auto
value_impl(T const & t, PriorityTag<1>, value_by_ref)
-> decltype(value_impl(
    atlas_value_for(t),
    value_tag{},
    value_by_ref{}))
{
    return value_impl(atlas_value_for(t), value_tag{}, value_by_ref{});
}
template <typename T>
constexpr auto
value_impl(T & t, PriorityTag<1>, value_by_val)
-> decltype(value_impl(
    atlas_value_for(std::move(t)),
    value_tag{},
    value_by_val{}))
{
    return value_impl(atlas_value_for(std::move(t)), value_tag{}, value_by_val{});
}
template <typename T>
constexpr auto
value_impl(T const & t, PriorityTag<1>, value_by_val)
-> decltype(value_impl(
    atlas_value_for(t),
    value_tag{},
    value_by_val{}))
{
    return value_impl(atlas_value_for(t), value_tag{}, value_by_val{});
}

struct ToUnderlying
{
    template <typename T>
    constexpr auto
    operator () (T & t) const
    -> decltype(atlas_detail::value_impl(t, value_tag{}, value_by_ref{}))
    {
        return atlas_detail::value_impl(t, value_tag{}, value_by_ref{});
    }

    template <typename T>
    constexpr auto
    operator () (T const & t) const
    -> decltype(atlas_detail::value_impl(t, value_tag{}, value_by_ref{}))
    {
        return atlas_detail::value_impl(t, value_tag{}, value_by_ref{});
    }

    template <
        typename T,
        when<not std::is_lvalue_reference<T>::value> = true>
    constexpr auto
    operator () (T && t) const
    -> decltype(atlas_detail::value_impl(t, value_tag{}, value_by_val{}))
    {
        return atlas_detail::value_impl(t, value_tag{}, value_by_val{});
    }
};

// ----------------------------------------------------------------------------
// Unwrap: Remove exactly one layer from atlas types or enums
// Unlike undress, this does NOT recurse.
// ----------------------------------------------------------------------------

template <typename T>
constexpr auto
unwrap_impl(T & t, PriorityTag<2>)
-> decltype(atlas_value_for(t))
{
    return atlas_value_for(t);
}

template <typename T>
constexpr auto
unwrap_impl(T const & t, PriorityTag<2>)
-> decltype(atlas_value_for(t))
{
    return atlas_value_for(t);
}

template <typename T>
constexpr auto
unwrap_impl(T && t, PriorityTag<2>)
-> typename std::enable_if<
    not std::is_lvalue_reference<T>::value,
    decltype(atlas_value_for(std::move(t)))>::type
{
    return atlas_value_for(std::move(t));
}

// Enum fallback - convert to underlying type
template <typename T>
constexpr auto
unwrap_impl(T t, PriorityTag<1>)
-> typename std::enable_if<
    std::is_enum<T>::value,
    typename std::underlying_type<T>::type>::type
{
    return static_cast<typename std::underlying_type<T>::type>(t);
}

// No PriorityTag<0> - SFINAE failure for non-atlas/non-enum types

struct Unwrap
{
    template <typename T>
    constexpr auto
    operator () (T & t) const
    -> decltype(unwrap_impl(t, PriorityTag<2>{}))
    {
        return unwrap_impl(t, PriorityTag<2>{});
    }

    template <typename T>
    constexpr auto
    operator () (T const & t) const
    -> decltype(unwrap_impl(t, PriorityTag<2>{}))
    {
        return unwrap_impl(t, PriorityTag<2>{});
    }

    template <
        typename T,
        when<not std::is_lvalue_reference<T>::value> = true>
    constexpr auto
    operator () (T && t) const
    -> decltype(unwrap_impl(std::forward<T>(t), PriorityTag<2>{}))
    {
        return unwrap_impl(std::forward<T>(t), PriorityTag<2>{});
    }
};

// ----------------------------------------------------------------------------
// UndressEnum: Drill through atlas types and stop at enum
// Like undress, but stops at enum instead of converting to underlying type.
// SFINAE fails if the drill does not resolve to an enum.
// ----------------------------------------------------------------------------
using undress_enum_tag = PriorityTag<1>;

// Base case: T is an enum - return it (don't convert to underlying)
template <typename T>
constexpr auto
undress_enum_impl(T & t, PriorityTag<0>)
-> typename std::enable_if<std::is_enum<T>::value, T &>::type
{
    return t;
}

template <typename T>
constexpr auto
undress_enum_impl(T const & t, PriorityTag<0>)
-> typename std::enable_if<std::is_enum<T>::value, T const &>::type
{
    return t;
}

// Base case: rvalue enum - return by value (avoids dangling reference)
template <typename T>
constexpr auto
undress_enum_impl(T && t, PriorityTag<0>)
-> typename std::enable_if<
    not std::is_lvalue_reference<T>::value && std::is_enum<T>::value,
    T>::type
{
    return t;
}

// Recursive case: drill through atlas types
template <typename T>
constexpr auto
undress_enum_impl(T & t, PriorityTag<1>)
-> decltype(undress_enum_impl(atlas_value_for(t), undress_enum_tag{}))
{
    return undress_enum_impl(atlas_value_for(t), undress_enum_tag{});
}

template <typename T>
constexpr auto
undress_enum_impl(T const & t, PriorityTag<1>)
-> decltype(undress_enum_impl(atlas_value_for(t), undress_enum_tag{}))
{
    return undress_enum_impl(atlas_value_for(t), undress_enum_tag{});
}

template <typename T>
constexpr auto
undress_enum_impl(T && t, PriorityTag<1>)
-> typename std::enable_if<
    not std::is_lvalue_reference<T>::value,
    decltype(undress_enum_impl(atlas_value_for(std::move(t)), undress_enum_tag{}))>::type
{
    return undress_enum_impl(atlas_value_for(std::move(t)), undress_enum_tag{});
}

struct UndressEnum
{
    template <typename T>
    constexpr auto
    operator () (T & t) const
    -> decltype(undress_enum_impl(t, undress_enum_tag{}))
    {
        return undress_enum_impl(t, undress_enum_tag{});
    }

    template <typename T>
    constexpr auto
    operator () (T const & t) const
    -> decltype(undress_enum_impl(t, undress_enum_tag{}))
    {
        return undress_enum_impl(t, undress_enum_tag{});
    }

    template <
        typename T,
        when<not std::is_lvalue_reference<T>::value> = true>
    constexpr auto
    operator () (T && t) const
    -> decltype(undress_enum_impl(std::forward<T>(t), undress_enum_tag{}))
    {
        return undress_enum_impl(std::forward<T>(t), undress_enum_tag{});
    }
};

// ----------------------------------------------------------------------------
// Type trait: holds_enum - true if undress_enum would succeed
// Uses the same mechanism as undress_enum to ensure consistency.
// ----------------------------------------------------------------------------
template <typename T, typename = void>
struct holds_enum_impl : std::false_type {};

template <typename T>
struct holds_enum_impl<
    T,
    void_t<decltype(undress_enum_impl(
        std::declval<remove_cvref_t<T> &>(),
        undress_enum_tag{}))>>
: std::true_type {};

using cast_tag = PriorityTag<1>;

// Trait to check if static_cast<TargetT>(U) is well-formed.
template <typename TargetT, typename U, typename = void>
struct is_directly_castable : std::false_type {};

template <typename TargetT, typename U>
struct is_directly_castable<TargetT, U,
    void_t<decltype(static_cast<TargetT>(std::declval<U>()))>>
: std::true_type {};

// Recursive castability check via struct template specialization.
// GCC evaluates trailing return types of function template overloads eagerly
// during overload resolution -- before checking enable_if default arguments --
// which causes infinite recursion when the trailing return type contains a
// recursive call to cast_impl.  Struct template partial specializations do not
// have this problem: the enable_if in the third parameter is fully resolved
// before the base class (which carries the recursive check) is instantiated.
template <typename TargetT, typename U, typename = void>
struct can_cast_impl;

template <typename TargetT, typename U, typename = void>
struct can_cast_via_unwrap : std::false_type {};

template <typename TargetT, typename U>
struct can_cast_via_unwrap<TargetT, U,
    void_t<decltype(atlas_value_for(std::declval<U>()))>>
: can_cast_impl<TargetT, decltype(atlas_value_for(std::declval<U>()))> {};

template <typename TargetT, typename U, typename>
struct can_cast_impl : can_cast_via_unwrap<TargetT, U> {};

template <typename TargetT, typename U>
struct can_cast_impl<TargetT, U,
    void_t<decltype(static_cast<TargetT>(std::declval<U>()))>>
: std::true_type {};

// ----------------------------------------------------------------------------
// cast_impl: Drill down to find the first type castable to TargetT
// ----------------------------------------------------------------------------
template <typename TargetT, typename U>
constexpr auto
cast_impl(U && u, PriorityTag<1>)
-> decltype(static_cast<TargetT>(std::forward<U>(u)))
{
    return static_cast<TargetT>(std::forward<U>(u));
}

// Reference target + rvalue source: use ref_tag path (no temporaries)
template <
    typename TargetT, typename U,
    typename std::enable_if<
        can_cast_impl<TargetT, U>::value &&
        !is_directly_castable<TargetT, U>::value &&
        std::is_reference<TargetT>::value &&
        !std::is_lvalue_reference<U>::value,
        bool>::type = true>
constexpr TargetT
cast_impl(U && u, PriorityTag<0>)
{
    return cast_impl<TargetT>(
        atlas_value_for(std::move(u), ref_tag{}), cast_tag{});
}

// Everything else: lvalue sources already return refs; value targets are safe
template <
    typename TargetT, typename U,
    typename std::enable_if<
        can_cast_impl<TargetT, U>::value &&
        !is_directly_castable<TargetT, U>::value &&
        (!std::is_reference<TargetT>::value ||
         std::is_lvalue_reference<U>::value),
        bool>::type = true>
constexpr TargetT
cast_impl(U && u, PriorityTag<0>)
{
    return cast_impl<TargetT>(atlas_value_for(std::forward<U>(u)), cast_tag{});
}

template <typename TargetT>
struct CastTo
{
    template <typename U>
    constexpr auto
    operator () (U && u) const
    -> decltype(cast_impl<TargetT>(std::forward<U>(u), cast_tag{}))
    {
        return cast_impl<TargetT>(std::forward<U>(u), cast_tag{});
    }
};

void begin();
void end();

template <typename T>
constexpr auto
begin_(T && t) noexcept(noexcept(begin(std::forward<T>(t))))
-> decltype(begin(std::forward<T>(t)))
{
    return begin(std::forward<T>(t));
}

template <typename T>
constexpr auto
end_(T && t) noexcept(noexcept(end(std::forward<T>(t))))
-> decltype(end(std::forward<T>(t)))
{
    return end(std::forward<T>(t));
}

// ----------------------------------------------------------------------------
// from_atlas_cast support utilities
// ----------------------------------------------------------------------------

template <typename FromT, typename ToT>
using forward_like_t = typename std::conditional<
    is_lref<FromT>::value,
    ToT const &,
    ToT &&>::type;

template <typename SourceT, typename TargetT, typename = void>
struct is_atlas_castable : std::false_type {};

template <typename SourceT, typename TargetT>
struct is_atlas_castable<SourceT, TargetT,
    void_t<decltype(cast_impl<TargetT const &>(
        std::declval<remove_cvref_t<SourceT> const &>(), cast_tag{}))>>
: std::true_type {};

} // namespace atlas_detail

using atlas_detail::enable_if_t;
using atlas_detail::remove_cv_t;
using atlas_detail::remove_cvref_t;
using atlas_detail::when;

template <typename T>
using is_atlas_type = atlas_detail::has_atlas_value_type<T>;

template <typename T>
using holds_enum = atlas_detail::holds_enum_impl<atlas_detail::remove_cvref_t<T>>;

#if defined(__cpp_concepts) && __cpp_concepts >= 201907L
template <typename T>
concept AtlasTypeC = is_atlas_type<T>::value;

template <typename T>
concept HoldsEnumC = holds_enum<T>::value;
#endif

#if defined(__cpp_inline_variables) && __cpp_inline_variables >= 201606L
inline constexpr auto undress = atlas_detail::ToUnderlying{};
#elif defined(__cpp_variable_templates) && __cpp_variable_templates >= 201304L
constexpr auto undress = atlas_detail::ToUnderlying{};
#else
// fallback: not nice, but not terrible and prevents ADL
namespace {
constexpr atlas_detail::ToUnderlying undress{};
}
#endif

#if defined(__cpp_inline_variables) && __cpp_inline_variables >= 201606L
inline constexpr auto unwrap = atlas_detail::Unwrap{};
#elif defined(__cpp_variable_templates) && __cpp_variable_templates >= 201304L
constexpr auto unwrap = atlas_detail::Unwrap{};
#else
namespace {
constexpr atlas_detail::Unwrap unwrap{};
}
#endif

#if defined(__cpp_inline_variables) && __cpp_inline_variables >= 201606L
inline constexpr auto undress_enum = atlas_detail::UndressEnum{};
#elif defined(__cpp_variable_templates) && __cpp_variable_templates >= 201304L
constexpr auto undress_enum = atlas_detail::UndressEnum{};
#else
namespace {
constexpr atlas_detail::UndressEnum undress_enum{};
}
#endif

#if defined(__cpp_inline_variables) && __cpp_inline_variables >= 201606L
template <typename TargetT>
inline constexpr atlas_detail::CastTo<TargetT> cast{};
#elif defined(__cpp_variable_templates) && __cpp_variable_templates >= 201304L
template <typename TargetT>
constexpr atlas_detail::CastTo<TargetT> cast{};
#else
// fallback: function template (ADL still possible, but unavoidable in C++11)
template <typename TargetT, typename U>
constexpr auto
cast(U && u)
-> decltype(atlas_detail::cast_impl<TargetT>(
    std::forward<U>(u),
    atlas_detail::cast_tag{}))
{
    return atlas_detail::cast_impl<TargetT>(
        std::forward<U>(u),
        atlas_detail::cast_tag{});
}
#endif

} // namespace atlas

#endif // WJH_ATLAS_50E620B544874CB8BE4412EE6773BF90

#ifndef WJH_ATLAS_771333B44A11491895F986933BB2FB41
#define WJH_ATLAS_771333B44A11491895F986933BB2FB41
namespace atlas {
namespace atlas_detail {
// ----------------------------------------------------------------------------
// Hash drilling support
// ----------------------------------------------------------------------------

// is_hashable<T>: detects if std::hash<T> is valid
template <typename T, typename = void>
struct is_hashable
: std::false_type
{ };

template <typename T>
struct is_hashable<
    T,
    void_t<decltype(std::hash<T>{}(std::declval<T const &>()))>>
: std::true_type
{ };

// Base case: T is directly hashable
template <typename T>
auto hash_drill(T const & t, PriorityTag<2>)
-> typename std::enable_if<
    is_hashable<T>::value,
    std::size_t>::type
{
    return std::hash<T>{}(t);
}

// Enum fallback: T is an enum without std::hash, use underlying type
template <typename T>
auto hash_drill(T const & t, PriorityTag<1>)
-> typename std::enable_if<
    std::is_enum<T>::value &&
    not is_hashable<T>::value,
    std::size_t>::type
{
    return std::hash<typename std::underlying_type<T>::type>{}(
        static_cast<typename std::underlying_type<T>::type>(t));
}

// Recursive case: T is an atlas type, drill down
template <typename T>
auto hash_drill(T const & t, PriorityTag<0>)
-> decltype(hash_drill(atlas_value_for(t), PriorityTag<2>{}))
{
    return hash_drill(atlas_value_for(t), PriorityTag<2>{});
}
} // namespace atlas_detail
} // namespace atlas
#endif // WJH_ATLAS_771333B44A11491895F986933BB2FB41

#ifndef WJH_ATLAS_60461ED5AEEF4509B86FB80C8B1E0FE0
#define WJH_ATLAS_60461ED5AEEF4509B86FB80C8B1E0FE0
namespace atlas {
namespace atlas_detail {
// ----------------------------------------------------------------------------
// OStream drilling support
// ----------------------------------------------------------------------------

// is_ostreamable<T>: detects if T can be written to std::ostream
template <typename T, typename = void>
struct is_ostreamable
: std::false_type
{ };

template <typename T>
struct is_ostreamable<
    T,
    void_t<decltype(std::declval<std::ostream &>() << std::declval<T const &>())>>
: std::true_type
{ };

// Base case: T is directly ostreamable
template <typename T>
auto ostream_drill(std::ostream & strm, T const & t, PriorityTag<2>)
-> typename std::enable_if<
    is_ostreamable<T>::value,
    std::ostream &>::type
{
    return strm << t;
}

// Enum fallback: T is an enum without operator<<, use underlying type
template <typename T>
auto ostream_drill(std::ostream & strm, T const & t, PriorityTag<1>)
-> typename std::enable_if<
    std::is_enum<T>::value &&
    not is_ostreamable<T>::value,
    std::ostream &>::type
{
    return strm << static_cast<typename std::underlying_type<T>::type>(t);
}

// Recursive case: T is an atlas type, drill down
template <typename T>
auto ostream_drill(std::ostream & strm, T const & t, PriorityTag<0>)
-> decltype(ostream_drill(strm, atlas_value_for(t), PriorityTag<2>{}))
{
    return ostream_drill(strm, atlas_value_for(t), PriorityTag<2>{});
}
} // namespace atlas_detail
} // namespace atlas
#endif // WJH_ATLAS_60461ED5AEEF4509B86FB80C8B1E0FE0

#ifndef WJH_ATLAS_4296E303C8F846C0B958EB450C57465B
#define WJH_ATLAS_4296E303C8F846C0B958EB450C57465B
namespace atlas {
namespace atlas_detail {
// ----------------------------------------------------------------------------
// IStream drilling support
// ----------------------------------------------------------------------------

// is_istreamable<T>: detects if T can be read from std::istream
template <typename T, typename = void>
struct is_istreamable
: std::false_type
{ };

template <typename T>
struct is_istreamable<
    T,
    void_t<decltype(std::declval<std::istream &>() >> std::declval<T &>())>>
: std::true_type
{ };

// Base case: T is directly istreamable
template <typename T>
auto istream_drill(std::istream & strm, T & t, PriorityTag<2>)
-> typename std::enable_if<
    is_istreamable<T>::value,
    std::istream &>::type
{
    return strm >> t;
}

// Enum fallback: T is an enum without operator>>, read as underlying type
template <typename T>
auto istream_drill(std::istream & strm, T & t, PriorityTag<1>)
-> typename std::enable_if<
    std::is_enum<T>::value &&
    not is_istreamable<T>::value,
    std::istream &>::type
{
    typename std::underlying_type<T>::type tmp;
    strm >> tmp;
    t = static_cast<T>(tmp);
    return strm;
}

// Recursive case: T is an atlas type, drill down
template <typename T>
auto istream_drill(std::istream & strm, T & t, PriorityTag<0>)
-> decltype(istream_drill(strm, atlas_value_for(t), PriorityTag<2>{}))
{
    return istream_drill(strm, atlas_value_for(t), PriorityTag<2>{});
}
} // namespace atlas_detail
} // namespace atlas
#endif // WJH_ATLAS_4296E303C8F846C0B958EB450C57465B

#ifndef WJH_ATLAS_9B74AE244B4F4EB68DF9D80B67E1EB05
#define WJH_ATLAS_9B74AE244B4F4EB68DF9D80B67E1EB05
namespace atlas {
namespace atlas_detail {
// ----------------------------------------------------------------------------
// Format drilling support (C++20+)
// ----------------------------------------------------------------------------
#if defined(__cpp_lib_format) && __cpp_lib_format >= 202110L

// Concept: T is formattable via std::formatter<T>
template <typename T>
concept formattable = requires(
    std::formatter<T> f,
    T const & t,
    std::format_parse_context & parse_ctx,
    std::format_context & fmt_ctx)
{
    f.parse(parse_ctx);
    f.format(t, fmt_ctx);
};

// Drill to find a formattable type, returning a reference or converted value
template <typename T>
constexpr decltype(auto) format_value_drill(T const & t)
{
    if constexpr (formattable<T>) {
        // Base case: T is directly formattable - return reference
        return (t);
    } else if constexpr (std::is_enum_v<T>) {
        // Enum fallback: convert to underlying type
        return static_cast<std::underlying_type_t<T>>(t);
    } else if constexpr (has_atlas_value_type<T>::value) {
        // Recursive case: drill through atlas type
        return format_value_drill(atlas_value_for(t));
    } else {
        static_assert(formattable<T>, "Type is not formattable after drilling");
    }
}

// Type trait for the drilled type
template <typename T>
using format_drilled_type_t =
    std::remove_cvref_t<decltype(format_value_drill(std::declval<T const &>()))>;

#endif // __cpp_lib_format
} // namespace atlas_detail
} // namespace atlas
#endif // WJH_ATLAS_9B74AE244B4F4EB68DF9D80B67E1EB05

#ifndef WJH_ATLAS_83B11BF12B6945019DF71C7517A1D6DA
#define WJH_ATLAS_83B11BF12B6945019DF71C7517A1D6DA
#if __cplusplus >= 202002L
namespace atlas::atlas_detail {

// Concept: T is an atlas type whose underlying value chain is eventually
// hashable
template <typename T>
concept atlas_hashable = has_atlas_value_type<T>::value &&
    requires(T const & t) {
        { hash_drill(atlas_value_for(t), PriorityTag<2>{}) }
            -> std::same_as<std::size_t>;
    };

} // namespace atlas::atlas_detail

template <typename T>
    requires atlas::atlas_detail::atlas_hashable<T>
struct std::hash<T>
{
    std::size_t operator()(T const & t) const
    noexcept(noexcept(atlas::atlas_detail::hash_drill(
        atlas_value_for(t), atlas::atlas_detail::PriorityTag<2>{})))
    {
        return atlas::atlas_detail::hash_drill(
            atlas_value_for(t), atlas::atlas_detail::PriorityTag<2>{});
    }
};
#else // pre-C++20
namespace atlas {
namespace atlas_detail {

// Base class for per-type std::hash specializations.
// The template <typename U = T> trick defers instantiation of the
// return type until operator() is actually called, providing a
// SFINAE-like effect for most cases. Note: this relies on hash_drill
// producing a substitution failure (not a hard error) for non-hashable
// types, which holds for all atlas-generated types.
template <typename T>
struct hash_base
{
    template <typename U = T>
    ATLAS_NODISCARD
    auto operator()(U const & t) const
    noexcept(noexcept(hash_drill(
        atlas_value_for(t), PriorityTag<2>{})))
    -> decltype(hash_drill(
        atlas_value_for(t), PriorityTag<2>{}))
    {
        return hash_drill(
            atlas_value_for(t), PriorityTag<2>{});
    }
};

} // namespace atlas_detail
} // namespace atlas
#endif // C++20
#endif // WJH_ATLAS_83B11BF12B6945019DF71C7517A1D6DA

#ifndef WJH_ATLAS_A3A2ADA707CA47BE9EB94254C729C906
#define WJH_ATLAS_A3A2ADA707CA47BE9EB94254C729C906
#if defined(__cpp_lib_format) && __cpp_lib_format >= 202110L
namespace atlas::atlas_detail {

// Concept: T is an atlas type whose underlying value chain is eventually
// formattable
template <typename T>
concept atlas_formattable = has_atlas_value_type<T>::value &&
    requires(T const & t) {
        format_value_drill(atlas_value_for(t));
    };

} // namespace atlas::atlas_detail

template <typename T>
    requires atlas::atlas_detail::atlas_formattable<T>
struct std::formatter<T>
{
private:
    using drilled_type_ =
        atlas::atlas_detail::format_drilled_type_t<typename T::atlas_value_type>;
    std::formatter<drilled_type_> underlying_formatter_;

public:
    constexpr auto parse(std::format_parse_context & ctx)
    {
        return underlying_formatter_.parse(ctx);
    }

    auto format(T const & t, std::format_context & ctx) const
    {
        return underlying_formatter_.format(
            atlas::atlas_detail::format_value_drill(atlas_value_for(t)),
            ctx);
    }
};
#endif // __cpp_lib_format
#endif // WJH_ATLAS_A3A2ADA707CA47BE9EB94254C729C906

#ifndef WJH_ATLAS_204DEDF8AD1A4B8EA2910C659C4523BC
#define WJH_ATLAS_204DEDF8AD1A4B8EA2910C659C4523BC
namespace atlas {

// Templated operator<< for all atlas types
// ADL finds this via atlas::strong_type_tag base class
template <typename T>
auto operator<<(std::ostream & strm, T const & t)
-> typename std::enable_if<
    atlas_detail::has_atlas_value_type<T>::value,
    decltype(atlas_detail::ostream_drill(
        strm, atlas_value_for(t), atlas_detail::PriorityTag<2>{}))>::type
{
    return atlas_detail::ostream_drill(
        strm, atlas_value_for(t), atlas_detail::PriorityTag<2>{});
}

} // namespace atlas
#endif // WJH_ATLAS_204DEDF8AD1A4B8EA2910C659C4523BC

#ifndef WJH_ATLAS_8E1585765002403FBFA3B92531F0A25E
#define WJH_ATLAS_8E1585765002403FBFA3B92531F0A25E
namespace atlas {

// Templated operator>> for all atlas types
// ADL finds this via atlas::strong_type_tag base class
template <typename T>
auto operator>>(std::istream & strm, T & t)
-> typename std::enable_if<
    atlas_detail::has_atlas_value_type<T>::value,
    decltype(atlas_detail::istream_drill(
        strm, atlas_value_for(t), atlas_detail::PriorityTag<2>{}))>::type
{
    return atlas_detail::istream_drill(
        strm, atlas_value_for(t), atlas_detail::PriorityTag<2>{});
}

} // namespace atlas
#endif // WJH_ATLAS_8E1585765002403FBFA3B92531F0A25E


//////////////////////////////////////////////////////////////////////
///
/// These are the droids you are looking for!
///
//////////////////////////////////////////////////////////////////////


namespace aipp {

/**
 * @brief Strong type wrapper for std::int64_t
 *
 * Generated by Atlas Strong Type Generator.
 * Generation parameters:
 * - kind: class
 * - type_namespace: aipp
 * - type_name: Foo
 * - description: std::int64_t; <=>
 * - default_value: ""
 */
class Foo
: private atlas::strong_type_tag<Foo>
{
    std::int64_t value;

public:
    using atlas_value_type = std::int64_t;

    constexpr explicit Foo() = default;

    template <
        typename... ArgTs,
        typename std::enable_if<
            std::is_constructible<std::int64_t, ArgTs...>::value,
            bool>::type = true>
    constexpr explicit Foo(ArgTs && ... args)
    : value(std::forward<ArgTs>(args)...)
    { }

    /**
     * Access to immediate underlying value via ADL.
     */
    friend constexpr std::int64_t const & atlas_value_for(Foo const & self) noexcept {
        return self.value;
    }
    friend constexpr std::int64_t & atlas_value_for(Foo & self) noexcept {
        return self.value;
    }
    friend constexpr auto atlas_value_for(Foo && self) noexcept
        -> typename std::enable_if<
            std::is_move_constructible<std::int64_t>::value,
            std::int64_t>::type
    {
        return std::move(self.value);
    }
    friend constexpr auto atlas_value_for(
        Foo && self,
        atlas::atlas_detail::ref_tag) noexcept
        -> std::int64_t &&
    {
        return static_cast<std::int64_t &&>(self.value);
    }

#if defined(__cpp_impl_three_way_comparison) && \
    __cpp_impl_three_way_comparison >= 201907L
    /**
     * The default three-way comparison (spaceship) operator.
     */
    friend constexpr auto operator <=> (
        Foo const &,
        Foo const &) = default;
#else
    /**
     * Comparison operators (C++17 fallback for spaceship operator).
     * In C++20+, these are synthesized from operator<=>.
     */
    friend constexpr bool operator < (
        Foo const & lhs,
        Foo const & rhs)
    noexcept(noexcept(std::declval<std::int64_t const &>() <
        std::declval<std::int64_t const &>()))
    {
        return lhs.value < rhs.value;
    }

    friend constexpr bool operator <= (
        Foo const & lhs,
        Foo const & rhs)
    noexcept(noexcept(std::declval<std::int64_t const &>() <=
        std::declval<std::int64_t const &>()))
    {
        return lhs.value <= rhs.value;
    }

    friend constexpr bool operator > (
        Foo const & lhs,
        Foo const & rhs)
    noexcept(noexcept(std::declval<std::int64_t const &>() >
        std::declval<std::int64_t const &>()))
    {
        return lhs.value > rhs.value;
    }

    friend constexpr bool operator >= (
        Foo const & lhs,
        Foo const & rhs)
    noexcept(noexcept(std::declval<std::int64_t const &>() >=
        std::declval<std::int64_t const &>()))
    {
        return lhs.value >= rhs.value;
    }
#endif

#if defined(__cpp_impl_three_way_comparison) && \
    __cpp_impl_three_way_comparison >= 201907L
    /**
     * The default equality comparison operator.
     * Provided with spaceship operator for optimal performance.
     */
    friend constexpr bool operator == (
        Foo const &,
        Foo const &) = default;
#else
    /**
     * Equality comparison operators (C++17 fallback).
     * In C++20+, these are synthesized from operator<=>.
     */
    friend constexpr bool operator == (
        Foo const & lhs,
        Foo const & rhs)
    noexcept(noexcept(std::declval<std::int64_t const &>() ==
        std::declval<std::int64_t const &>()))
    {
        return lhs.value == rhs.value;
    }

    friend constexpr bool operator != (
        Foo const & lhs,
        Foo const & rhs)
    noexcept(noexcept(std::declval<std::int64_t const &>() !=
        std::declval<std::int64_t const &>()))
    {
        return lhs.value != rhs.value;
    }
#endif
};
} // namespace aipp


#if __cplusplus < 202002L
template <>
struct std::hash<aipp::Foo>
: atlas::atlas_detail::hash_base<aipp::Foo>
{};
#endif

namespace aipp {

/**
 * @brief Strong type wrapper for std::size_t
 *
 * Generated by Atlas Strong Type Generator.
 * Generation parameters:
 * - kind: class
 * - type_namespace: aipp
 * - type_name: Capacity
 * - description: std::size_t; <=>
 * - default_value: ""
 */
class Capacity
: private atlas::strong_type_tag<Capacity>
{
    std::size_t value;

public:
    using atlas_value_type = std::size_t;

    constexpr explicit Capacity() = default;

    template <
        typename... ArgTs,
        typename std::enable_if<
            std::is_constructible<std::size_t, ArgTs...>::value,
            bool>::type = true>
    constexpr explicit Capacity(ArgTs && ... args)
    : value(std::forward<ArgTs>(args)...)
    { }

    /**
     * Access to immediate underlying value via ADL.
     */
    friend constexpr std::size_t const & atlas_value_for(Capacity const & self) noexcept {
        return self.value;
    }
    friend constexpr std::size_t & atlas_value_for(Capacity & self) noexcept {
        return self.value;
    }
    friend constexpr auto atlas_value_for(Capacity && self) noexcept
        -> typename std::enable_if<
            std::is_move_constructible<std::size_t>::value,
            std::size_t>::type
    {
        return std::move(self.value);
    }
    friend constexpr auto atlas_value_for(
        Capacity && self,
        atlas::atlas_detail::ref_tag) noexcept
        -> std::size_t &&
    {
        return static_cast<std::size_t &&>(self.value);
    }

#if defined(__cpp_impl_three_way_comparison) && \
    __cpp_impl_three_way_comparison >= 201907L
    /**
     * The default three-way comparison (spaceship) operator.
     */
    friend constexpr auto operator <=> (
        Capacity const &,
        Capacity const &) = default;
#else
    /**
     * Comparison operators (C++17 fallback for spaceship operator).
     * In C++20+, these are synthesized from operator<=>.
     */
    friend constexpr bool operator < (
        Capacity const & lhs,
        Capacity const & rhs)
    noexcept(noexcept(std::declval<std::size_t const &>() <
        std::declval<std::size_t const &>()))
    {
        return lhs.value < rhs.value;
    }

    friend constexpr bool operator <= (
        Capacity const & lhs,
        Capacity const & rhs)
    noexcept(noexcept(std::declval<std::size_t const &>() <=
        std::declval<std::size_t const &>()))
    {
        return lhs.value <= rhs.value;
    }

    friend constexpr bool operator > (
        Capacity const & lhs,
        Capacity const & rhs)
    noexcept(noexcept(std::declval<std::size_t const &>() >
        std::declval<std::size_t const &>()))
    {
        return lhs.value > rhs.value;
    }

    friend constexpr bool operator >= (
        Capacity const & lhs,
        Capacity const & rhs)
    noexcept(noexcept(std::declval<std::size_t const &>() >=
        std::declval<std::size_t const &>()))
    {
        return lhs.value >= rhs.value;
    }
#endif

#if defined(__cpp_impl_three_way_comparison) && \
    __cpp_impl_three_way_comparison >= 201907L
    /**
     * The default equality comparison operator.
     * Provided with spaceship operator for optimal performance.
     */
    friend constexpr bool operator == (
        Capacity const &,
        Capacity const &) = default;
#else
    /**
     * Equality comparison operators (C++17 fallback).
     * In C++20+, these are synthesized from operator<=>.
     */
    friend constexpr bool operator == (
        Capacity const & lhs,
        Capacity const & rhs)
    noexcept(noexcept(std::declval<std::size_t const &>() ==
        std::declval<std::size_t const &>()))
    {
        return lhs.value == rhs.value;
    }

    friend constexpr bool operator != (
        Capacity const & lhs,
        Capacity const & rhs)
    noexcept(noexcept(std::declval<std::size_t const &>() !=
        std::declval<std::size_t const &>()))
    {
        return lhs.value != rhs.value;
    }
#endif
};
} // namespace aipp


#if __cplusplus < 202002L
template <>
struct std::hash<aipp::Capacity>
: atlas::atlas_detail::hash_base<aipp::Capacity>
{};
#endif

namespace aipp {

/**
 * @brief Strong type wrapper for bool
 *
 * Generated by Atlas Strong Type Generator.
 * Generation parameters:
 * - kind: class
 * - type_namespace: aipp
 * - type_name: EnqueueResult
 * - description: bool; <=>
 * - default_value: ""
 */
class EnqueueResult
: private atlas::strong_type_tag<EnqueueResult>
{
    bool value;

public:
    using atlas_value_type = bool;

    constexpr explicit EnqueueResult() = default;

    template <
        typename... ArgTs,
        typename std::enable_if<
            std::is_constructible<bool, ArgTs...>::value,
            bool>::type = true>
    constexpr explicit EnqueueResult(ArgTs && ... args)
    : value(std::forward<ArgTs>(args)...)
    { }

    /**
     * Access to immediate underlying value via ADL.
     */
    friend constexpr bool const & atlas_value_for(EnqueueResult const & self) noexcept {
        return self.value;
    }
    friend constexpr bool & atlas_value_for(EnqueueResult & self) noexcept {
        return self.value;
    }
    friend constexpr auto atlas_value_for(EnqueueResult && self) noexcept
        -> typename std::enable_if<
            std::is_move_constructible<bool>::value,
            bool>::type
    {
        return std::move(self.value);
    }
    friend constexpr auto atlas_value_for(
        EnqueueResult && self,
        atlas::atlas_detail::ref_tag) noexcept
        -> bool &&
    {
        return static_cast<bool &&>(self.value);
    }

#if defined(__cpp_impl_three_way_comparison) && \
    __cpp_impl_three_way_comparison >= 201907L
    /**
     * The default three-way comparison (spaceship) operator.
     */
    friend constexpr auto operator <=> (
        EnqueueResult const &,
        EnqueueResult const &) = default;
#else
    /**
     * Comparison operators (C++17 fallback for spaceship operator).
     * In C++20+, these are synthesized from operator<=>.
     */
    friend constexpr bool operator < (
        EnqueueResult const & lhs,
        EnqueueResult const & rhs)
    noexcept(noexcept(std::declval<bool const &>() <
        std::declval<bool const &>()))
    {
        return lhs.value < rhs.value;
    }

    friend constexpr bool operator <= (
        EnqueueResult const & lhs,
        EnqueueResult const & rhs)
    noexcept(noexcept(std::declval<bool const &>() <=
        std::declval<bool const &>()))
    {
        return lhs.value <= rhs.value;
    }

    friend constexpr bool operator > (
        EnqueueResult const & lhs,
        EnqueueResult const & rhs)
    noexcept(noexcept(std::declval<bool const &>() >
        std::declval<bool const &>()))
    {
        return lhs.value > rhs.value;
    }

    friend constexpr bool operator >= (
        EnqueueResult const & lhs,
        EnqueueResult const & rhs)
    noexcept(noexcept(std::declval<bool const &>() >=
        std::declval<bool const &>()))
    {
        return lhs.value >= rhs.value;
    }
#endif

#if defined(__cpp_impl_three_way_comparison) && \
    __cpp_impl_three_way_comparison >= 201907L
    /**
     * The default equality comparison operator.
     * Provided with spaceship operator for optimal performance.
     */
    friend constexpr bool operator == (
        EnqueueResult const &,
        EnqueueResult const &) = default;
#else
    /**
     * Equality comparison operators (C++17 fallback).
     * In C++20+, these are synthesized from operator<=>.
     */
    friend constexpr bool operator == (
        EnqueueResult const & lhs,
        EnqueueResult const & rhs)
    noexcept(noexcept(std::declval<bool const &>() ==
        std::declval<bool const &>()))
    {
        return lhs.value == rhs.value;
    }

    friend constexpr bool operator != (
        EnqueueResult const & lhs,
        EnqueueResult const & rhs)
    noexcept(noexcept(std::declval<bool const &>() !=
        std::declval<bool const &>()))
    {
        return lhs.value != rhs.value;
    }
#endif
};
} // namespace aipp


#if __cplusplus < 202002L
template <>
struct std::hash<aipp::EnqueueResult>
: atlas::atlas_detail::hash_base<aipp::EnqueueResult>
{};
#endif

namespace aipp {

/**
 * @brief Strong type wrapper for bool
 *
 * Generated by Atlas Strong Type Generator.
 * Generation parameters:
 * - kind: class
 * - type_namespace: aipp
 * - type_name: ProducerSideIsFull
 * - description: bool; <=>
 * - default_value: ""
 */
class ProducerSideIsFull
: private atlas::strong_type_tag<ProducerSideIsFull>
{
    bool value;

public:
    using atlas_value_type = bool;

    constexpr explicit ProducerSideIsFull() = default;

    template <
        typename... ArgTs,
        typename std::enable_if<
            std::is_constructible<bool, ArgTs...>::value,
            bool>::type = true>
    constexpr explicit ProducerSideIsFull(ArgTs && ... args)
    : value(std::forward<ArgTs>(args)...)
    { }

    /**
     * Access to immediate underlying value via ADL.
     */
    friend constexpr bool const & atlas_value_for(ProducerSideIsFull const & self) noexcept {
        return self.value;
    }
    friend constexpr bool & atlas_value_for(ProducerSideIsFull & self) noexcept {
        return self.value;
    }
    friend constexpr auto atlas_value_for(ProducerSideIsFull && self) noexcept
        -> typename std::enable_if<
            std::is_move_constructible<bool>::value,
            bool>::type
    {
        return std::move(self.value);
    }
    friend constexpr auto atlas_value_for(
        ProducerSideIsFull && self,
        atlas::atlas_detail::ref_tag) noexcept
        -> bool &&
    {
        return static_cast<bool &&>(self.value);
    }

#if defined(__cpp_impl_three_way_comparison) && \
    __cpp_impl_three_way_comparison >= 201907L
    /**
     * The default three-way comparison (spaceship) operator.
     */
    friend constexpr auto operator <=> (
        ProducerSideIsFull const &,
        ProducerSideIsFull const &) = default;
#else
    /**
     * Comparison operators (C++17 fallback for spaceship operator).
     * In C++20+, these are synthesized from operator<=>.
     */
    friend constexpr bool operator < (
        ProducerSideIsFull const & lhs,
        ProducerSideIsFull const & rhs)
    noexcept(noexcept(std::declval<bool const &>() <
        std::declval<bool const &>()))
    {
        return lhs.value < rhs.value;
    }

    friend constexpr bool operator <= (
        ProducerSideIsFull const & lhs,
        ProducerSideIsFull const & rhs)
    noexcept(noexcept(std::declval<bool const &>() <=
        std::declval<bool const &>()))
    {
        return lhs.value <= rhs.value;
    }

    friend constexpr bool operator > (
        ProducerSideIsFull const & lhs,
        ProducerSideIsFull const & rhs)
    noexcept(noexcept(std::declval<bool const &>() >
        std::declval<bool const &>()))
    {
        return lhs.value > rhs.value;
    }

    friend constexpr bool operator >= (
        ProducerSideIsFull const & lhs,
        ProducerSideIsFull const & rhs)
    noexcept(noexcept(std::declval<bool const &>() >=
        std::declval<bool const &>()))
    {
        return lhs.value >= rhs.value;
    }
#endif

#if defined(__cpp_impl_three_way_comparison) && \
    __cpp_impl_three_way_comparison >= 201907L
    /**
     * The default equality comparison operator.
     * Provided with spaceship operator for optimal performance.
     */
    friend constexpr bool operator == (
        ProducerSideIsFull const &,
        ProducerSideIsFull const &) = default;
#else
    /**
     * Equality comparison operators (C++17 fallback).
     * In C++20+, these are synthesized from operator<=>.
     */
    friend constexpr bool operator == (
        ProducerSideIsFull const & lhs,
        ProducerSideIsFull const & rhs)
    noexcept(noexcept(std::declval<bool const &>() ==
        std::declval<bool const &>()))
    {
        return lhs.value == rhs.value;
    }

    friend constexpr bool operator != (
        ProducerSideIsFull const & lhs,
        ProducerSideIsFull const & rhs)
    noexcept(noexcept(std::declval<bool const &>() !=
        std::declval<bool const &>()))
    {
        return lhs.value != rhs.value;
    }
#endif
};
} // namespace aipp


#if __cplusplus < 202002L
template <>
struct std::hash<aipp::ProducerSideIsFull>
: atlas::atlas_detail::hash_base<aipp::ProducerSideIsFull>
{};
#endif

namespace aipp {

/**
 * @brief Strong type wrapper for bool
 *
 * Generated by Atlas Strong Type Generator.
 * Generation parameters:
 * - kind: class
 * - type_namespace: aipp
 * - type_name: ConsumerSideIsEmpty
 * - description: bool; <=>
 * - default_value: ""
 */
class ConsumerSideIsEmpty
: private atlas::strong_type_tag<ConsumerSideIsEmpty>
{
    bool value;

public:
    using atlas_value_type = bool;

    constexpr explicit ConsumerSideIsEmpty() = default;

    template <
        typename... ArgTs,
        typename std::enable_if<
            std::is_constructible<bool, ArgTs...>::value,
            bool>::type = true>
    constexpr explicit ConsumerSideIsEmpty(ArgTs && ... args)
    : value(std::forward<ArgTs>(args)...)
    { }

    /**
     * Access to immediate underlying value via ADL.
     */
    friend constexpr bool const & atlas_value_for(ConsumerSideIsEmpty const & self) noexcept {
        return self.value;
    }
    friend constexpr bool & atlas_value_for(ConsumerSideIsEmpty & self) noexcept {
        return self.value;
    }
    friend constexpr auto atlas_value_for(ConsumerSideIsEmpty && self) noexcept
        -> typename std::enable_if<
            std::is_move_constructible<bool>::value,
            bool>::type
    {
        return std::move(self.value);
    }
    friend constexpr auto atlas_value_for(
        ConsumerSideIsEmpty && self,
        atlas::atlas_detail::ref_tag) noexcept
        -> bool &&
    {
        return static_cast<bool &&>(self.value);
    }

#if defined(__cpp_impl_three_way_comparison) && \
    __cpp_impl_three_way_comparison >= 201907L
    /**
     * The default three-way comparison (spaceship) operator.
     */
    friend constexpr auto operator <=> (
        ConsumerSideIsEmpty const &,
        ConsumerSideIsEmpty const &) = default;
#else
    /**
     * Comparison operators (C++17 fallback for spaceship operator).
     * In C++20+, these are synthesized from operator<=>.
     */
    friend constexpr bool operator < (
        ConsumerSideIsEmpty const & lhs,
        ConsumerSideIsEmpty const & rhs)
    noexcept(noexcept(std::declval<bool const &>() <
        std::declval<bool const &>()))
    {
        return lhs.value < rhs.value;
    }

    friend constexpr bool operator <= (
        ConsumerSideIsEmpty const & lhs,
        ConsumerSideIsEmpty const & rhs)
    noexcept(noexcept(std::declval<bool const &>() <=
        std::declval<bool const &>()))
    {
        return lhs.value <= rhs.value;
    }

    friend constexpr bool operator > (
        ConsumerSideIsEmpty const & lhs,
        ConsumerSideIsEmpty const & rhs)
    noexcept(noexcept(std::declval<bool const &>() >
        std::declval<bool const &>()))
    {
        return lhs.value > rhs.value;
    }

    friend constexpr bool operator >= (
        ConsumerSideIsEmpty const & lhs,
        ConsumerSideIsEmpty const & rhs)
    noexcept(noexcept(std::declval<bool const &>() >=
        std::declval<bool const &>()))
    {
        return lhs.value >= rhs.value;
    }
#endif

#if defined(__cpp_impl_three_way_comparison) && \
    __cpp_impl_three_way_comparison >= 201907L
    /**
     * The default equality comparison operator.
     * Provided with spaceship operator for optimal performance.
     */
    friend constexpr bool operator == (
        ConsumerSideIsEmpty const &,
        ConsumerSideIsEmpty const &) = default;
#else
    /**
     * Equality comparison operators (C++17 fallback).
     * In C++20+, these are synthesized from operator<=>.
     */
    friend constexpr bool operator == (
        ConsumerSideIsEmpty const & lhs,
        ConsumerSideIsEmpty const & rhs)
    noexcept(noexcept(std::declval<bool const &>() ==
        std::declval<bool const &>()))
    {
        return lhs.value == rhs.value;
    }

    friend constexpr bool operator != (
        ConsumerSideIsEmpty const & lhs,
        ConsumerSideIsEmpty const & rhs)
    noexcept(noexcept(std::declval<bool const &>() !=
        std::declval<bool const &>()))
    {
        return lhs.value != rhs.value;
    }
#endif
};
} // namespace aipp


#if __cplusplus < 202002L
template <>
struct std::hash<aipp::ConsumerSideIsEmpty>
: atlas::atlas_detail::hash_base<aipp::ConsumerSideIsEmpty>
{};
#endif
#endif // AIPP_6F7C135EA1682095423401977B710E77BF617D9A
